---
title: "Association between polygenic risk scores and gene expression"
site: workflowr::wflow_site
author: "Jing Gu"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This is the guide page for the PRS project. Below are the links to analyses.

### **Project Goal**: 
The goal is to predict traits for GTEx dataset by building polygenic risk scores (PRS) based on effect sizes from GWAS summary statistics and then associate PRS with gene expression to understand how genetic effects influence and converge on genes or pathways that are important for complex traits. 

### **Data Availability**: 
  * Base data:     
        - Height GWAS summary statistics (no invidual genotype data)
        
  * Target data:    
        - WTCCC datasets(7 traits)
        - GTEx RNA-Seq individual level genotype data

### QC steps:

* [QC procedures for base and target dataset](Follow_guidlines.html)

### Evaluation of tools

* [Lassosum and PRSice-2](Evaluation_of_PRS_Tools.html)

### Results
* [Results](Lassosum_analysis.html)


### Metrics for variance explained
Regular $R^2$ for continuous trait outcomes  
Conceptual proxies pseudo-$R^2$  
- Nagelkerke  
- Lee (liability scale)  


